name: Lab Quiz CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Update
      run: sudo apt-get update

    - name: Install Valgrind
      run: sudo apt-get install -y valgrind

    - name: Compile
      run: make
      
    - name: Run Test
      run: valgrind ./td --leak-check=full
